version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Hub433"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-deyudex8jbmy"
s3_prefix = "Hub433"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
