AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for HelloWorld

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  Hub433Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Test
      Auth:
        DefaultAuthorizer: Hub433UsersAuthorizer
        Authorizers:
          Hub433UsersAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:us-west-1:254414866354:userpool/us-west-1_g4JeVFuCV
            Identity:
              Header: Authorization 
  CreateThingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/Hub433Backend/
      Handler: Hub433Backend::Hub433Backend.CreateThing::FunctionHandler
      Runtime: dotnetcore3.1
      Events:
        Hub433Api:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Hub433Api
            Auth:
              DefaultAuthorizer: Hub433UsersAuthorizer
            Path: /thing/create
            Method: get
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Hub433Api:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${Hub433Api}.execute-api.${AWS::Region}.amazonaws.com/Test/hello/"
  CreateThingFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt CreateThingFunction.Arn
  CreateThingFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CreateThingFunctionIamRole.Arn